jquants:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 4
      host: 'host.docker.internal'
      port: 5432
      user: "{{ env_var('DB_USER') }}"
      pass: "{{ env_var('DB_PASS') }}"
      dbname: "{{ env_var('DB_NAME') }}"
      schema: public
